spring:
  application:
    name: client-service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
gateway:
  url: http://localhost:8080