spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: backend-service
          uri: lb://backend-service
          predicates:
            - Path=/api/**
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO