server:
  port: 8082

spring:
  application:
    name: backend-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: backend-service-1-${random.value}
